channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.0.1
- pip:
  - mlflow==2.20.2
  - catboost==1.2.7
  - ipywidgets==8.1.5
  - numpy==1.26.4
  - pandas==2.2.3
  - scipy==1.15.2
name: mlflow-env
